### PR TITLE
User accounts and login

### PR DESCRIPTION
**Pull request by rsmithlal**
Add devise for user accounts and login

Add JSON authorization using JWT

### CODE REVIEW

**Comment by rsmithlal** [comment]
Hey @seb1441! Would you be interested in helping with the development of the JWT API authentication? If we get the JWT authentication working, we will be able to connect from the Better Together website to the API to start consuming the Community Engine API from the Vue front end and start building out the platform functionality! What do you think?

**Comment by seb1441** [comment]
Hey @rsmithlal, sorry for the late answer but sure!
I will let you know if I find anything that could be changed or improved.

**Comment by rsmithlal** [comment]
Awesome, thank you Seb! I'm close to releasing the alpha for the community engine API, so as soon as we can get JWT authorization implemented with Devise we will be able to start using the community engine to communicate and organize our activities. =)



---- On Wed, 23 Sep 2020 20:38:06 -0400 Sebastien <notifications@github.com> wrote ----





Hey https://github.com/rsmithlal, sorry for the late answer but sure!
 I will let you know if I find anything that could be changed or improved.

**Comment by rsmithlal** [comment]
@dependabot rebase

**Comment by rsmithlal** [comment]
Leaving this here for archival.

It was an early attempt at setting up user accounts and login using devise-jwt. Login is now handled through the community engine.

**Pull request closed without merging**
